configName: glcd_rgba8888_mxt_mzda_intddr_cu_wvga
folderName: blank_qs_mzda_cu_wvga
format_version: v1.0
frameworkPath: ..\..\..\..\harmony3_dev
processor: PIC32MZ2064DAR176
projectName: blank_quickstart_mzda_cu_wvga
settings:
  PackageFilter: audio;bsp;core;cryptoauthlib;csp;Devices;dev_packs;gfx;gfx-ed;harmony-services;net;quick_docs;touch;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32MZ-DA_DFP\1.4.118
