format_version: v1.0
type: UniqueComponent
attributes: {id: core}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: BSP_PIN_128_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: SDA2}
  - type: String
    attributes: {id: BSP_PIN_129_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: SCL2}
  - type: String
    attributes: {id: BSP_PIN_42_DIR}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: In}
  - type: String
    attributes: {id: BSP_PIN_42_FUNCTION_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: BSP_MAXTOUCH_CHG}
  - type: String
    attributes: {id: BSP_PIN_42_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: GPIO}
  - type: String
    attributes: {id: BSP_PIN_42_LAT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: ''}
  - type: String
    attributes: {id: BSP_PIN_79_DIR}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: Out}
  - type: String
    attributes: {id: BSP_PIN_79_FUNCTION_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: TM4301B_BACKLIGHT}
  - type: String
    attributes: {id: BSP_PIN_79_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: GPIO}
  - type: String
    attributes: {id: BSP_PIN_79_LAT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: High}
  - type: KeyValueSet
    attributes: {id: COMPILER_CHOICE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Boolean
    attributes: {id: CONFIG_SYS_CLK_REFCLK5_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_glcd, value: 'true'}
  - type: String
    attributes: {id: CONFIG_SYS_CLK_REFCLK5_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '200000000'}
  - type: Boolean
    attributes: {id: CORE_SOFTWARE_0_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: CORE_TIMER_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: 'true'}
  - type: Boolean
    attributes: {id: CORE_TIMER_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: CORE_TIMER_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: CORE_TIMER_InterruptHandler}
  - type: Boolean
    attributes: {id: CORE_TIMER_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: 'true'}
  - type: Boolean
    attributes: {id: DDR_CLOCK_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ddr, value: 'true'}
  - type: Integer
    attributes: {id: DDR_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '200000000'}
  - type: Boolean
    attributes: {id: EVIC_0_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_0_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: EVIC_0_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: CORE_TIMER_InterruptHandler}
  - type: Boolean
    attributes: {id: EVIC_148_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_148_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: EVIC_148_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: I2C2_BUS_InterruptHandler}
  - type: Boolean
    attributes: {id: EVIC_149_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_149_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: EVIC_149_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: I2C2_SLAVE_Handler}
  - type: Boolean
    attributes: {id: EVIC_150_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_150_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: EVIC_150_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: I2C2_MASTER_InterruptHandler}
  - type: Boolean
    attributes: {id: EVIC_192_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_192_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: EVIC_192_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: GLCD_Interrupt_Handler}
  - type: Boolean
    attributes: {id: EVIC_1_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_1_ENABLE_GENERATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_1_ENABLE_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_1_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_1_PRIORITY_GENERATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_1_PRIORITY_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_1_SUBPRIORITY_GENERATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_1_SUBPRIORITY_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_4_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_4_ENABLE_GENERATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_4_ENABLE_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_4_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_4_PRIORITY_GENERATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_4_PRIORITY_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_4_SUBPRIORITY_GENERATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_4_SUBPRIORITY_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Combo
    attributes: {id: EVIC_PRIORITY_1ATTRIBUTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: SRS}
  - type: Combo
    attributes: {id: EVIC_PRIORITY_2ATTRIBUTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: SRS}
  - type: Combo
    attributes: {id: EVIC_PRIORITY_3ATTRIBUTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: SRS}
  - type: Combo
    attributes: {id: EVIC_PRIORITY_4ATTRIBUTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: SRS}
  - type: Combo
    attributes: {id: EVIC_PRIORITY_5ATTRIBUTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: SRS}
  - type: Combo
    attributes: {id: EVIC_PRIORITY_6ATTRIBUTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: SRS}
  - type: Combo
    attributes: {id: EVIC_PRIORITY_7ATTRIBUTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: SRS}
  - type: Boolean
    attributes: {id: EVIC_SRS_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: GLCD_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_glcd, value: 'true'}
  - type: Boolean
    attributes: {id: GLCD_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: GLCD_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_glcd, value: GLCD_Interrupt_Handler}
  - type: Boolean
    attributes: {id: GLCD_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_glcd, value: 'true'}
  - type: Boolean
    attributes: {id: I2C2_BUS_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: 'true'}
  - type: Boolean
    attributes: {id: I2C2_BUS_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: I2C2_BUS_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: I2C2_BUS_InterruptHandler}
  - type: Boolean
    attributes: {id: I2C2_BUS_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: 'true'}
  - type: Boolean
    attributes: {id: I2C2_CLOCK_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: 'true'}
  - type: Integer
    attributes: {id: I2C2_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '100000000'}
  - type: Boolean
    attributes: {id: I2C2_MASTER_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: 'true'}
  - type: Boolean
    attributes: {id: I2C2_MASTER_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: I2C2_MASTER_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: I2C2_MASTER_InterruptHandler}
  - type: Boolean
    attributes: {id: I2C2_MASTER_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: 'true'}
  - type: Boolean
    attributes: {id: I2C2_SLAVE_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: 'false'}
  - type: Boolean
    attributes: {id: I2C2_SLAVE_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: I2C2_SLAVE_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: I2C2_SLAVE_Handler}
  - type: Boolean
    attributes: {id: I2C2_SLAVE_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: 'false'}
  - type: String
    attributes: {id: KEIL_STACK_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0x1200'}
  - type: Hex
    attributes: {id: PMD4_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '511'}
  - type: Hex
    attributes: {id: PMD5_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '807223103'}
  - type: Hex
    attributes: {id: PMD6_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '278986752'}
  - type: Hex
    attributes: {id: PMD7_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '5242880'}
  - type: String
    attributes: {id: REFO5TRIM_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0x0'}
  - type: String
    attributes: {id: REFOCON5_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0x200'}
  - type: Hex
    attributes: {id: SYS_PORT_D_LAT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '1'}
  - type: Hex
    attributes: {id: SYS_PORT_D_TRIS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '1'}
  - type: Hex
    attributes: {id: SYS_PORT_H_LAT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Hex
    attributes: {id: SYS_PORT_H_TRIS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Boolean
    attributes: {id: TIMER_1_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Integer
    attributes: {id: TMR1_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: KeyValueSet
    attributes: {id: clkSvcMode}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
- type: ElementPosition
  attributes: {x: '220', y: '20', id: core}
