format_version: v1.0
type: UniqueComponent
attributes: {id: sys_input}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: RTOSEnabled}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_input, value: 'false'}
- type: ElementPosition
  attributes: {x: '61', y: '398', id: sys_input}
