format_version: v1.0
type: UniqueComponent
attributes: {id: sys_fs}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SYS_FS_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: 'true'}
  - type: Boolean
    attributes: {id: SYS_FS_IDX1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: 'false'}
  - type: Boolean
    attributes: {id: SYS_FS_IDX2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: 'false'}
  - type: Boolean
    attributes: {id: SYS_FS_IDX3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: 'false'}
  - type: Integer
    attributes: {id: SYS_FS_MAX_FILES}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: String
    attributes: {id: SYS_FS_MEDIA_DEVICE_1_NAME_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: /dev/sda1}
      - type: User
        attributes: {value: /dev/sda1}
  - type: String
    attributes: {id: SYS_FS_MEDIA_DEVICE_2_NAME_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: /dev/sda2}
  - type: String
    attributes: {id: SYS_FS_MEDIA_DEVICE_3_NAME_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: /dev/sda3}
  - type: String
    attributes: {id: SYS_FS_MEDIA_DEVICE_4_NAME_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: /dev/sda4}
  - type: String
    attributes: {id: SYS_FS_MEDIA_MOUNT_1_NAME_IDX0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: /mnt/myDrive0}
  - type: Combo
    attributes: {id: SYS_FS_MEDIA_TYPE_DEFINE_IDX0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SYS_FS_MEDIA_TYPE_MSD}
  - type: Integer
    attributes: {id: SYS_FS_TOTAL_VOLUMES}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: '1'}
  - type: Integer
    attributes: {id: SYS_FS_VOLUME_NUMBER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: Attachments
  children:
  - type: MultiCapability
    attributes: {id: sys_fs_DRV_MEDIA_dependency}
    children:
    - type: TargetAttachments
      children:
      - type: TargetAttachment
        attributes: {targetComponentID: usb_host_msd, targetAttachmentID: USB Host
            MSD}
- type: ElementPosition
  attributes: {x: '192', y: '492', id: sys_fs}
