configName: glcd_rgba8888_mxt_mzda_intddr_cu_wvga
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MZ2064DAR176
projectName: ''
settings:
  PackageFilter: audio;bsp;core;cryptoauthlib;csp;Devices;dev_packs;gfx;gfx-ed;harmony-services;net;quick_docs;touch;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-DA_DFP\1.4.118\atdf\PIC32MZ2064DAR176.atdf
